// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI_dg7RKdvexBETk16CLfHKKBdIqiOLHY',
    appId: '1:1079591344212:web:cea7009b4498bbf27a35c1',
    messagingSenderId: '1079591344212',
    projectId: 'galaxy-ray',
    authDomain: 'galaxy-ray.firebaseapp.com',
    storageBucket: 'galaxy-ray.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwY2AG0HHrzkQlGVASEUtDigFIQqsn0G8',
    appId: '1:1079591344212:android:cca6d4071cc26ec87a35c1',
    messagingSenderId: '1079591344212',
    projectId: 'galaxy-ray',
    storageBucket: 'galaxy-ray.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRfUk9_7DXcrVtDTL2_7pHuuJV0Mh4PEc',
    appId: '1:1079591344212:ios:79d705d1f70608597a35c1',
    messagingSenderId: '1079591344212',
    projectId: 'galaxy-ray',
    storageBucket: 'galaxy-ray.appspot.com',
    iosBundleId: 'com.example.galaxyRay',
  );
}
